In [1]:
import torch
import numpy as np

In [2]:
# creating tensors

# directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [10]:
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr)

In [32]:
x_np.equal(x_data)

True

In [36]:
# from another tensor
x_ones = torch.ones_like(x_data)
print(f'Ones tensor: \n {x_ones}')
print(f'Ones tensor shape: {x_ones.shape}, data_type: {x_ones.dtype}\n')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random tensor: \n {x_rand}')
print(f'Random tensor shape: {x_rand.shape}, data_type: {x_rand.dtype}')

Ones tensor: 
 tensor([[1, 1],
        [1, 1]])
Ones tensor shape: torch.Size([2, 2]), data_type: torch.int64

Random tensor: 
 tensor([[0.2627, 0.5958],
        [0.6759, 0.1259]])
Random tensor shape: torch.Size([2, 2]), data_type: torch.float32


In [44]:
# With random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.4267, 0.5323, 0.4023],
        [0.0937, 0.0078, 0.7373]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [48]:
# tensor attrs
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [49]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print('gpu available, tensor moved to cuda')

In [51]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [60]:
# joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [69]:
# multiplying tensors

# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

print(f"tensor.mul(r_t) \n {tensor.mul(r_t)} \n")
print(f"tensor * r_t \n {tensor * r_t}")


tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.mul(r_t) 
 tensor([[0.3322, 0.0000, 0.3222, 0.0013],
        [0.1955, 0.0000, 0.2758, 0.8635],
        [0.5121, 0.0000, 0.3227, 0.2452],
        [0.0968, 0.0000, 0.3314, 0.3527]]) 

tensor * r_t 
 tensor([[0.3322, 0.0000, 0.3222, 0.0013],
        [0.1955, 0.0000, 0.2758, 0.8635],
        [0.5121, 0.0000, 0.3227, 0.2452],
        [0.0968, 0.0000, 0.3314, 0.3527]])


In [73]:
# matrix multiply tensors

# note the transpose operation in the first case
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor)} \n")


tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor.matmul(tensor.T) 
 tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]]) 



In [76]:
# operations that have a `_` suffix are in-place
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [77]:
# tensors on CPU and numpy arrays share underlying memory

# tensor to np array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [78]:
# numpy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
